name: Continuous Integration workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible and Ansible Lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint

    - name: Run Ansible Lint
      run: ansible-lint playbooks/dmw_part_one.yaml

    - name: Run Ansible Syntax Check
      run: ansible-playbook --syntax-check playbooks/dmw_part_one.yaml
